# Generated by Django 5.2.1 on 2025-06-02 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soeid', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='SOEID must be in the format of 2 letters followed by 5 numbers (e.g., xy60697).', regex='^[a-zA-Z]{2}\\d{5}$')])),
            ],
        ),
    ]
