# Generated by Django 5.2.1 on 2025-06-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Grade must be in the format of 1 letter followed by 2 digits (e.g., C05, C10).', regex='^[A-Z]\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
