# Generated by Django 5.2.1 on 2025-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
